swg_manager_appearance:
    resource: "@AnhSwgManagerBundle/Controller/AppearanceController.php"
    type: annotation

swg_manager_character:
    resource: "@AnhSwgManagerBundle/Controller/CharacterController.php"
    type: annotation

swg_manager_component:
    resource: "@AnhSwgManagerBundle/Controller/ComponentController.php"
    type: annotation

swg_manager_entity:
    resource: "@AnhSwgManagerBundle/Controller/EntityController.php"
    type: annotation

swg_manager_entity_template:
    resource: "@AnhSwgManagerBundle/Controller/EntityTemplateController.php"
    type: annotation

swg_manager_player:
    resource: "@AnhSwgManagerBundle/Controller/PlayerController.php"
    type: annotation

swg_manager_scene:
    resource: "@AnhSwgManagerBundle/Controller/SceneController.php"
    type: annotation